update-mime-database: Improve use of g_string_free()
The existing code wasn’t incorrect, but it did trigger warnings with
more modern versions of GLib, because to the compiler it looked like the
built string had been leaked:
```
In file included from /opt/gnome/install/include/glib-2.0/glib/giochannel.h:36,
                 from /opt/gnome/install/include/glib-2.0/glib.h:56,
                 from ../../source/shared-mime-info/src/update-mime-database.cpp:14:
../../source/shared-mime-info/src/update-mime-database.cpp: In function ‘void match_value_and_mask(Match*, xmlNode*, GError**)’:
/opt/gnome/install/include/glib-2.0/glib/gstring.h:73:31: error: ignoring return value of ‘gchar* g_string_free_and_steal(GString*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
   73 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../../source/shared-mime-info/src/update-mime-database.cpp:1488:17: note: in expansion of macro ‘g_string_free’
 1488 |                 g_string_free(parsed_value, FALSE);
      |                 ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Rearrange the code to make the ownership transfer more explicit.

Signed-off-by: Philip Withnall <pwithnall@gnome.org>